name: cloudevents-haskell
version: 0.2.0.0
maintainer: Freckle Education
category: Utils
github: freckle/cloudevents-haskell
license: BSD-3-Clause
synopsis: Unofficial Haskell SDK for the CloudEvents specification
description: See the README on GitHub at <https://github.com/freckle/cloudevents-haskell#readme>

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - package.yaml

language: GHC2021

dependencies:
  - base < 5

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
      - -Wno-missing-poly-kind-signatures
  - condition: "impl(ghc >= 9.2)"
    ghc-options:
      - -Wno-missing-kind-signatures
  - condition: "impl(ghc >= 8.10)"
    ghc-options:
      - -Wno-missing-safe-haskell-mode
      - -Wno-prepositive-qualified-module
  - condition: "impl(ghc >= 8.8)"
    ghc-options:
      - -fwrite-ide-info

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoPostfixOperators
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - autodocodec
    - autodocodec-schema
    - binary
    - binary-instances
    - bytestring
    - hw-kafka-client
    - iri
    - lens
    - text
    - time
# tests:
#   spec:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
#     dependencies:
#       - cloudevents-haskell
#       - hspec
#       - hspec-junit-formatter
